<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Authors>elouafi.dev</Authors>
    <Company>elouafi.dev</Company>
    <Product>Xtream API SDK</Product>
    <Copyright>Copyright (c) 2026 elouafi.dev</Copyright>
  </PropertyGroup>

</Project>
